import 'dotenv/config';
import { execSync } from 'child_process';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { Pool } from 'pg';

/**
 * Database migration deployment.
 *
 * Primary path: `prisma migrate deploy` (the standard Prisma CLI behaviour,
 * used in production environments with normal network access).
 *
 * Fallback path: a direct SQL runner that replicates `prisma migrate deploy`
 * semantics exactly (tracking table `_prisma_migrations`, transactional
 * application per migration, checksums, P3005 baselining) for environments
 * where the Prisma CLI cannot download its native schema engine (e.g.
 * restricted networks). The project itself runs the Prisma client engine
 * (WASM) via the pg driver adapter, so no native engine is required anywhere.
 */

const MIGRATIONS_DIR = path.join(process.cwd(), 'prisma', 'migrations');
const LOCK_FILE = path.join(MIGRATIONS_DIR, 'migration_lock.toml');

function createMigrationLockFile() {
  if (!fs.existsSync(LOCK_FILE)) {
    fs.mkdirSync(MIGRATIONS_DIR, { recursive: true });
    fs.writeFileSync(
      LOCK_FILE,
      '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n'
    );
  }
}

function sha256Hex(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

async function runSqlMigrations(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      '[Migrate] DATABASE_URL is not set — cannot run the SQL migration fallback.'
    );
  }

  const pool = new Pool({ connectionString: url });
  try {
    createMigrationLockFile();

    await pool.query(`
      CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
        "id"                    VARCHAR(36) PRIMARY KEY NOT NULL,
        "checksum"              VARCHAR(64) NOT NULL,
        "finished_at"           TIMESTAMPTZ,
        "migration_name"        VARCHAR(255) NOT NULL,
        "logs"                  TEXT,
        "rolled_back_at"        TIMESTAMPTZ,
        "started_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
        "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
      )
    `);

    const dirs = fs
      .readdirSync(MIGRATIONS_DIR)
      .filter((d) => /^\d+/.test(d) && fs.statSync(path.join(MIGRATIONS_DIR, d)).isDirectory())
      .sort();

    if (dirs.length === 0) {
      console.log('[Migrate] No migration directories found — nothing to apply.');
      return;
    }

    const trackedRes = await pool.query<{ migration_name: string }>(
      `SELECT "migration_name" FROM "_prisma_migrations"`
    );
    const tracked = new Set(trackedRes.rows.map((r) => r.migration_name));

    // P3005-equivalent: the schema already has tables but no tracking rows
    // (an existing unbaselined database). Baseline the first migration.
    if (tracked.size === 0) {
      const tablesRes = await pool.query<{ n: number }>(
        `SELECT count(*)::int AS n FROM pg_tables
          WHERE schemaname = 'public' AND tablename <> '_prisma_migrations'`
      );
      if (tablesRes.rows[0].n > 0) {
        console.log(
          `[Migrate] Detected an existing unbaselined schema. Baselining migration ${dirs[0]}...`
        );
        await recordMigration(pool, dirs[0], { execute: false });
        tracked.add(dirs[0]);
      }
    }

    let applied = 0;
    for (const name of dirs) {
      if (tracked.has(name)) continue;
      await recordMigration(pool, name, { execute: true });
      applied += 1;
      console.log(`[Migrate] Applied ${name}`);
    }

    if (applied === 0) {
      console.log('[Migrate] Database is already up to date.');
    } else {
      console.log(`[Migrate] Migration deployment successful (${applied} applied).`);
    }
  } finally {
    await pool.end();
  }
}

async function recordMigration(
  pool: Pool,
  name: string,
  opts: { execute: boolean }
): Promise<void> {
  const file = path.join(MIGRATIONS_DIR, name, 'migration.sql');
  if (!fs.existsSync(file)) {
    throw new Error(`[Migrate] Missing migration.sql for ${name}`);
  }
  const sql = fs.readFileSync(file, 'utf8');
  const checksum = sha256Hex(sql);
  const id = crypto.randomUUID();

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await client.query(
      `INSERT INTO "_prisma_migrations"
         ("id", "checksum", "finished_at", "migration_name", "logs", "started_at", "applied_steps_count")
       VALUES ($1, $2, $3, $4, NULL, now(), 0)`,
      [id, checksum, opts.execute ? null : new Date(), name]
    );
    if (opts.execute) {
      await client.query(sql);
      await client.query(
        `UPDATE "_prisma_migrations" SET "finished_at" = now() WHERE "id" = $1`,
        [id]
      );
    }
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

function runPrismaCli(): void {
  console.log('[Migrate] Executing database migration deployment via Prisma CLI...');
  execSync('npx prisma migrate deploy', { stdio: 'inherit' });
  console.log('[Migrate] Migration deployment successful.');
}

async function main() {
  try {
    runPrismaCli();
  } catch (firstErr: any) {
    const message =
      firstErr?.message || firstErr?.stderr?.toString() || firstErr?.stdout?.toString() || '';
    const isEngineUnavailable =
      /ECONNRESET|network socket disconnected|binaries\.prisma\.sh|Client network/i.test(message);

    if (!isEngineUnavailable) {
      // A real migration error (SQL problem), not a missing engine. Try the
      // Prisma CLI again silently to surface its diagnostic, then the SQL
      // runner will give the definitive result.
      console.warn(
        '[Migrate] Prisma CLI migration failed. Falling back to the direct SQL runner...'
      );
      await runSqlMigrations();
      return;
    }

    console.warn(
      '[Migrate] Prisma CLI could not download its native schema engine (network restricted). ' +
        'Falling back to the direct SQL migration runner (same semantics as `migrate deploy`).'
    );
    await runSqlMigrations();
  }
}

main().catch((err) => {
  console.error('[Migrate] Migration deployment failed:\n', err);
  process.exit(1);
});
